### ISSUE TITLE
Support MDX

### ISSUE THREAD

**Issue by axelboc** [takumisoft68/vscode-markdown-table#24]
Unless I've done something wrong, the extension doesn't seem to work on MDX files. Would you consider supporting this file type?

**Comment by takumisoft68** [comment]
@axelboc 
I don't know MDX file. Is it a foo.mdx?

This extention doesn't work with .mdx files, because it isn't a common markdown file extention.

FYI, you can add unique file extention to vscode by setting 'files.associations' preference.
(https://code.visualstudio.com/docs/languages/identifiers)
You possibly use this extention by adding '*.mdx' to 'markdown' in 'files.associations'.

**Comment by axelboc** [comment]
MDX is a language that allows writing JSX code in Markdown files. If I treat `*.mdx` as markdown, I loose MDX support. 😢 

MDX is becoming quite mainstream in the React ecosystem. It's supported by Next.js, Create React App, Gatsby and Storybook to name a few.
